name: CI Pipeline

on:
  push:
    branches: [ main, phase/* ]
  pull_request:
    branches: [ main, phase/* ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run pre-commit hooks
      run: |
        pre-commit install
        pre-commit run --all-files
    
    - name: Run tests with coverage
      run: |
        pytest --cov=backend --cov-report=xml --cov-report=term-missing
    
    - name: Check code formatting
      run: |
        black --check backend/
        isort --check-only backend/
    
    - name: Lint code
      run: |
        flake8 backend/ --max-line-length=88 --extend-ignore=E203,W503
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: false

  security:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install safety
    
    - name: Check for security vulnerabilities
      run: |
        safety check --full-report
